[host]
name = "caveviewer"
domain = "caverobotics.com"
email = "tyler.hansen028@gmail.com"

[source]
branch = "main"

[deploy]
build_command = "npm install . && npm run build"
publish_directory = "dist"
