services:
  caveviewer:
    image: d3lta12/caveviewer
    build:
      context: ../
      dockerfile: docker/Dockerfile
    volumes:
      - ./files/caverobotics.com:/etc/letsencrypt/archive/caverobotics.com
      - ./files/caverobotics.com_symlinks:/etc/letsencrypt/live/caverobotics.com
    ports:
      - "80:80"
      - "443:443"